version: "3"
services:
  db:
    container_name: mysql-80 #il dois etre unique
    image: mysql:8.4
    platform: linux/amd64
    ports:
      - "8037:3306" # Dans docker on a cote interne donc notre machine donc on peut mettre celui que on veut ca c'est celui de gauche du coup et celui de droite cest le port qui est ouvert cotes docker et la cest le par default
    restart: always
    environment: #ceest des configuration
      MYSQL_DATABASE: app_db
    #  MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'#variable qui dis que ya pas de mdp
      MYSQL_ROOT_PASSWORD: ort
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes: #les deux points veut dire tu me prend tout ce qui a dans var... et tu menvoie sur dbdata
      - ./dbdata:/var/lib/mysql
  phpmyadmin:
    container_name: pma-80
    image: phpmyadmin/phpmyadmin
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 1G
      MEMORY_LIMIT: 512M
      MAX_EXECUTION_TIME: 0
    restart: always
    links:
      - db
#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - "8081:8080"
#    environment:
#      ADMINER_DEFAULT_SERVER: db
#      ADMINER_DESIGN: "lucas-sandery"
#    links:
#      - db
volumes:
  dbdata:
